apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: student0-wordpress
spec:
  destination:
    name: ''
    namespace: student-0
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 18.0.10
    chart: wordpress
  project: default
