---
# Documentation: https://kubernetes.io/docs/reference/access-authn-authz/rbac/
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list
rules:
  - apiGroups: [""]
    resources: [pods]
    verbs: [list]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: Role
  name: pods-list
  apiGroup: rbac.authorization.k8s.io
